<a href="https://colab.research.google.com/github/fuadh246/BDC_RA/blob/main/PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch_Fundamentals

In [8]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


# Intro to tensors
## Creating tensors

In [13]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [14]:
scalar.ndim

0

In [15]:
scalar.item()

7

In [17]:
# vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [18]:
vector.ndim

1

In [19]:
vector.shape

torch.Size([2])

In [22]:
# matrix
matrix = torch.tensor([[1,2],[1,2]])
matrix

tensor([[1, 2],
        [1, 2]])

In [23]:
matrix.ndim

2

In [24]:
matrix.shape

torch.Size([2, 2])

In [25]:
matrix[1]

tensor([1, 2])

In [26]:
matrix[1][1]

tensor(2)

In [28]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],[3,4,5],[6,7,8]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 4, 5],
         [6, 7, 8]]])

In [29]:
TENSOR.shape

torch.Size([1, 3, 3])

In [30]:
TENSOR.ndim

3

### Random tensor

In [41]:
### Random tensor

# create a random tensor of size (2,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[2.5251e-01, 3.3710e-02, 2.0612e-01, 8.8256e-01],
        [3.0415e-01, 7.6615e-01, 5.9207e-02, 1.4298e-02],
        [8.0086e-01, 4.0257e-01, 8.5759e-04, 8.1971e-02]])

In [42]:
random_tensor.ndim

2

In [46]:
random_tensor_size_tensor = torch.rand(size=(3,224,224)) # height, width, color
random_tensor_size_tensor.shape, random_tensor_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

Zeros and ones

In [49]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [50]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [51]:
ones.dtype

torch.float32

## range of torch

In [65]:
one_to_ten=torch.arange(start=0,end=10,step=1)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
ten_zeros= torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Float 32 tensor

In [68]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],dtype=torch.float16)
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float16)